"use client";

import { Client, Databases, Account, Storage, Functions } from 'appwrite';

// --- Environment Variables ---
export const APPWRITE_PROJECT_ID = import.meta.env.VITE_APPWRITE_PROJECT_ID || 'YOUR_APPWRITE_PROJECT_ID';
export const APPWRITE_ENDPOINT = import.meta.env.VITE_APPWRITE_ENDPOINT || 'https://cloud.appwrite.io/v1'; 
export const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID || 'YOUR_APPWRITE_DATABASE_ID';

// --- Collection IDs ---
export const APPWRITE_PRODUCTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_PRODUCTS_COLLECTION_ID || 'YOUR_PRODUCTS_COLLECTION_ID';
export const APPWRITE_USER_PROFILES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_USER_PROFILES_COLLECTION_ID || 'YOUR_USER_PROFILES_COLLECTION_ID';
export const APPWRITE_TRANSACTIONS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_TRANSACTIONS_COLLECTION_ID || 'YOUR_TRANSACTIONS_COLLECTION_ID';
export const APPWRITE_DEVELOPER_MESSAGES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_DEVELOPER_MESSAGES_COLLECTION_ID || 'YOUR_DEVELOPER_MESSAGES_COLLECTION_ID';
export const APPWRITE_REPORTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_REPORTS_COLLECTION_ID || 'YOUR_REPORTS_COLLECTION_ID';
export const APPWRITE_BLOCKED_WORDS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_BLOCKED_WORDS_COLLECTION_ID || 'YOUR_BLOCKED_WORDS_COLLECTION_ID';
export const APPWRITE_MISSING_COLLEGES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_MISSING_COLLEGES_COLLECTION_ID || 'YOUR_MISSING_COLLEGES_COLLECTION_ID';
export const APPWRITE_CANTEEN_COLLECTION_ID = import.meta.env.VITE_APPWRITE_CANTEEN_COLLECTION_ID || 'YOUR_CANTEEN_COLLECTION_ID';
export const APPWRITE_FOOD_ORDERS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_FOOD_ORDERS_COLLECTION_ID || 'YOUR_FOOD_ORDERS_COLLECTION_ID';
export const APPWRITE_BARGAIN_REQUESTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_BARGAIN_REQUESTS_COLLECTION_ID || 'YOUR_BARGAIN_REQUESTS_COLLECTION_ID';
export const APPWRITE_TOURNAMENTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_TOURNAMENTS_COLLECTION_ID || 'YOUR_TOURNAMENTS_COLLECTION_ID';
export const APPWRITE_CASH_EXCHANGE_COLLECTION_ID = import.meta.env.VITE_APPWRITE_CASH_EXCHANGE_COLLECTION_ID || 'YOUR_CASH_EXCHANGE_COLLECTION_ID';
export const APPWRITE_LOST_FOUND_COLLECTION_ID = import.meta.env.VITE_APPWRITE_LOST_FOUND_COLLECTION_ID || 'YOUR_LOST_FOUND_COLLECTION_ID';
export const APPWRITE_SERVICES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SERVICES_COLLECTION_ID || 'YOUR_SERVICES_COLLECTION_ID';
export const APPWRITE_SERVICE_REVIEWS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SERVICE_REVIEWS_COLLECTION_ID || 'YOUR_SERVICE_REVIEWS_COLLECTION_ID';
export const APPWRITE_ERRANDS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_ERRANDS_COLLECTION_ID || 'YOUR_ERRANDS_COLLECTION_ID';
export const APPWRITE_COLLABORATORS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_COLLABORATORS_COLLECTION_ID || 'YOUR_COLLABORATORS_COLLECTION_ID';
export const APPWRITE_AMBASSADOR_APPLICATIONS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_AMBASSADOR_APPLICATIONS_COLLECTION_ID || 'YOUR_AMBASSADOR_APPLICATIONS_COLLECTION_ID';
export const APPWRITE_CHAT_ROOMS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_CHAT_ROOMS_COLLECTION_ID || 'YOUR_CHAT_ROOMS_COLLECTION_ID';
export const APPWRITE_CHAT_MESSAGES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_CHAT_MESSAGES_COLLECTION_ID || 'YOUR_CHAT_MESSAGES_COLLECTION_ID';
export const APPWRITE_REGISTRATIONS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_CHAT_MESSAGES_COLLECTION_ID || 'YOUR_REGISTRATIONS_COLLECTION_ID';

// --- Bucket IDs ---
export const APPWRITE_COLLEGE_ID_BUCKET_ID = import.meta.env.VITE_APPWRITE_COLLEGE_ID_BUCKET_ID || 'YOUR_COLLEGE_ID_BUCKET_ID';

// --- Client Initialization ---
const client = new Client();

client
  .setEndpoint(APPWRITE_ENDPOINT)
  .setProject(APPWRITE_PROJECT_ID);

// --- Exports ---
export const account = new Account(client);
export const databases = new Databases(client);
export const storage = new Storage(client);
export const functions = new Functions(client); // Added Functions export

export default client;