// This file should contain your Appwrite client setup and configuration.

import { Client, Account, Databases, Storage } from 'appwrite'; // Import Storage

export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID || 'YOUR_APPWRITE_PROJECT_ID';
export const APPWRITE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID || 'YOUR_APPWRITE_DATABASE_ID';
export const APPWRITE_USER_PROFILES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_USER_PROFILES_COLLECTION_ID || 'YOUR_USER_PROFILES_COLLECTION_ID';
export const APPWRITE_TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_TRANSACTIONS_COLLECTION_ID || 'YOUR_TRANSACTIONS_COLLECTION_ID';
export const APPWRITE_DEVELOPER_MESSAGES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_DEVELOPER_MESSAGES_COLLECTION_ID || 'YOUR_DEVELOPER_MESSAGES_COLLECTION_ID';
export const APPWRITE_SERVICES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_SERVICES_COLLECTION_ID || 'YOUR_SERVICES_COLLECTION_ID';
export const APPWRITE_BARGAIN_REQUESTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_BARGAIN_REQUESTS_COLLECTION_ID || 'YOUR_BARGAIN_REQUESTS_COLLECTION_ID';
export const APPWRITE_ERRANDS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_ERRANDS_COLLECTION_ID || 'YOUR_ERRANDS_COLLECTION_ID';
export const APPWRITE_REPORTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_REPORTS_COLLECTION_ID || 'YOUR_REPORTS_COLLECTION_ID';
export const APPWRITE_FOOD_ORDERS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_FOOD_ORDERS_COLLECTION_ID || 'YOUR_FOOD_ORDERS_COLLECTION_ID';
export const APPWRITE_CANTEEN_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_CANTEEN_COLLECTION_ID || 'YOUR_CANTEEN_COLLECTION_ID';
export const APPWRITE_MARKETPLACE_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_MARKETPLACE_COLLECTION_ID || 'YOUR_MARKETPLACE_COLLECTION_ID';
export const APPWRITE_PRODUCTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PRODUCTS_COLLECTION_ID || 'YOUR_PRODUCTS_COLLECTION_ID';
export const APPWRITE_TOURNAMENTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_TOURNAMENTS_COLLECTION_ID || 'YOUR_TOURNAMENTS_COLLECTION_ID';
export const APPWRITE_CASH_EXCHANGE_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_CASH_EXCHANGE_COLLECTION_ID || 'YOUR_CASH_EXCHANGE_COLLECTION_ID';
export const APPWRITE_LOST_FOUND_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_LOST_FOUND_COLLECTION_ID || 'YOUR_LOST_FOUND_COLLECTION_ID';
export const APPWRITE_COLLABORATORS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLABORATORS_COLLECTION_ID || 'YOUR_COLLABORATORS_COLLECTION_ID';
export const APPWRITE_MISSING_COLLEGES_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_MISSING_COLLEGES_COLLECTION_ID || 'YOUR_MISSING_COLLEGES_COLLECTION_ID';
export const APPWRITE_SERVICE_REVIEWS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_SERVICE_REVIEWS_COLLECTION_ID || 'YOUR_SERVICE_REVIEWS_COLLECTION_ID';
export const APPWRITE_COLLEGE_ID_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLEGE_ID_BUCKET_ID || 'YOUR_COLLEGE_ID_BUCKET_ID'; // Added


const client = new Client();

client
  .setEndpoint('https://cloud.appwrite.io/v1') // Your API Endpoint
  .setProject(APPWRITE_PROJECT_ID); // Your project ID

const account = new Account(client);
const databases = new Databases(client);
const storage = new Storage(client); // Initialize Storage

export { client, account, databases, storage }; // Export storage