export const colleges = [
  { "id": "college1", "name": "Anna University" },
  { "id": "college2", "name": "VIT Vellore" },
  { "id": "college3", "name": "SRM Institute of Science and Technology" },
  { "id": "college4", "name": "PSG College of Technology" },
  { "id": "college5", "name": "SSN College of Engineering" },
  { "id": "college6", "name": "Coimbatore Institute of Technology" },
  { "id": "college7", "name": "Madras Institute of Technology" },
  { "id": "college8", "name": "Thiagarajar College of Engineering" },
  { "id": "college9", "name": "Kumaraguru College of Technology" },
  { "id": "college10", "name": "Easwari Engineering College" },
  { "id": "college11", "name": "St. Joseph's College of Engineering" },
  { "id": "college12", "name": "K.S. Rangasamy College of Technology" },
  { "id": "college13", "name": "Kongu Engineering College" },
  { "id": "college14", "name": "Bannari Amman Institute of Technology" },
  { "id": "college15", "name": "Velammal Engineering College" },
  { "id": "college16", "name": "Panimalar Engineering College" },
  { "id": "college17", "name": "Saveetha Engineering College" },
  { "id": "college18", "name": "Rajalakshmi Engineering College" },
  { "id": "college19", "name": "Meenakshi Sundararajan Engineering College" },
  { "id": "college20", "name": "Jerusalem College of Engineering" },
  { "id": "college21", "name": "Chennai Institute of Technology" },
  { "id": "college22", "name": "Sri Sairam Engineering College" },
  { "id": "college23", "name": "Adhiyamaan College of Engineering" },
  { "id": "college24", "name": "Government College of Technology, Coimbatore" },
  { "id": "college25", "name": "Karunya Institute of Technology and Sciences" },
  { "id": "college26", "name": "Sona College of Technology" },
  { "id": "college27", "name": "Vellore Institute of Technology, Chennai" },
  { "id": "college28", "name": "Amrita Vishwa Vidyapeetham, Coimbatore" },
  { "id": "college29", "name": "SRM Valliammai Engineering College" },
  { "id": "college30", "name": "Hindusthan College of Engineering and Technology" },
  { "id": "college31", "name": "KPR Institute of Engineering and Technology" },
  { "id": "college32", "name": "M. Kumarasamy College of Engineering" },
  { "id": "college33", "name": "P.S.G. Institute of Technology and Applied Research" },
  { "id": "college34", "name": "R.M.K. Engineering College" },
  { "id": "college35", "name": "Sri Krishna College of Engineering and Technology" },
  { "id": "college36", "name": "Sri Venkateswara College of Engineering" },
  { "id": "college37", "name": "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology" },
  { "id": "college38", "name": "Vivekanandha College of Engineering for Women" },
  { "id": "college39", "name": "Dr. Mahalingam College of Engineering and Technology" },
  { "id": "college40", "name": "Francis Xavier Engineering College" },
  { "id": "college41", "name": "G.H. Raisoni College of Engineering" },
  { "id": "college42", "name": "Government College of Engineering, Salem" },
  { "id": "college43", "name": "K. Ramakrishnan College of Engineering" },
  { "id": "college44", "name": "Mepco Schlenk Engineering College" },
  { "id": "college45", "name": "National Engineering College" },
  { "id": "college46", "name": "P.A. College of Engineering and Technology" },
  { "id": "college47", "name": "PSG College of Arts and Science" },
  { "id": "college48", "name": "S.A. Engineering College" },
  { "id": "college49", "name": "Sri Ramakrishna Engineering College" },
  { "id": "college50", "name": "St. Peter's Institute of Higher Education and Research" }
];