export const largeIndianColleges = [
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",
  "Indian Institute of Science (IISc) Bangalore",
  "Indian Institute of Management Ahmedabad (IIMA)",
  "Indian Institute of Management Bangalore (IIMB)",
  "Indian Institute of Management Calcutta (IIMC)",
  "All India Institute of Medical Sciences (AIIMS) Delhi",
  "Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER)",
  "National Law School of India University (NLSIU) Bangalore",
  "Indian Statistical Institute (ISI) Kolkata",
  "National Institute of Technology Tiruchirappalli",
  "National Institute of Technology Karnataka",
  "National Institute of Technology Warangal",
  "National Institute of Technology Calicut",
  "National Institute of Technology Rourkela",
  "Indian Institute of Information Technology, Allahabad",
  "Indian Institute of Information Technology, Bangalore",
  "Indian Institute of Information Technology, Hyderabad",
  "Vellore Institute of Technology",
  "Vellore Institute of Technology, Amaravati",
  "Vellore Institute of Technology, Bhopal",
  "SRM Institute of Science and Technology",
  "SRM University, Chennai",
  "Anna University",
  "Amrita Vishwa Vidyapeetham",
  "Manipal Academy of Higher Education",
  "Manipal University Jaipur",
  "Birla Institute of Technology and Science, Pilani",
  "BITS Pilani Goa Campus",
  "BITS Pilani Hyderabad Campus",
  "Delhi Technological University",
  "Netaji Subhas University of Technology",
  "Jadavpur University",
  "Osmania University",
  "University of Delhi",
  "Mumbai University",
  "Bangalore University",
  "Pune University",
  "Jawaharlal Nehru University",
  "Banaras Hindu University",
  "Aligarh Muslim University",
  "University of Hyderabad",
  "Jamia Millia Islamia",
  "Lovely Professional University",
  "Lovely Professional University, Phagwara",
  "Chandigarh University",
  "Chandigarh University, Mohali",
  "KIIT University",
  "KIIT University, Bhubaneswar",
  "Amity University Noida",
  "Amity University, Mumbai",
  "Amity University, Jaipur",
  "Christ University Bangalore",
  "Christ University, Delhi NCR",
  "Christ University, Pune",
  "Symbiosis International University",
  "Symbiosis Institute of Technology, Pune",
  "Presidency University Bangalore",
  "Presidency University, Kolkata",
  "Shiv Nadar University",
  "Shiv Nadar University, Chennai",
  "Ashoka University",
  "Ashoka University, Sonipat",
  "O.P. Jindal Global University",
  "O.P. Jindal Global University, Sonipat",
  "Thapar Institute of Engineering & Technology",
  "Thapar Institute of Engineering & Technology, Patiala",
  "Graphic Era University",
  "Graphic Era Deemed University, Dehradun",
  "Graphic Era Hill University, Dehradun",
  "Galgotias University",
  "Galgotias University, Greater Noida",
  "Galgotias University, Noida",
  "Sharda University",
  "Sharda University, Greater Noida",
  "Sharda University, Noida",
  "Bennett University",
  "Bennett University, Greater Noida",
  "Kalasalingam Academy of Research and Education",
  "Kalasalingam Academy of Research and Education, Krishnankoil",
  "Kalasalingam Academy of Research and Education, Srivilliputhur",
  "Sathyabama Institute of Science and Technology",
  "PSG College of Technology",
  "Coimbatore Institute of Technology",
  "Madras Institute of Technology",
  "College of Engineering, Guindy",
  "SSN College of Engineering",
  "Easwari Engineering College",
  "St. Joseph's College of Engineering",
  "Rajalakshmi Engineering College",
  "Saveetha Engineering College",
  "Hindustan Institute of Technology & Science",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
  "Bharath Institute of Higher Education and Research",
  "Dr. M.G.R. Educational and Research Institute",
  "SRM Valliammai Engineering College",
  "Panimalar Engineering College",
  "Jeppiaar Engineering College",
  "Anna Adarsh College for Women",
  "Loyola College, Chennai",
  "Madras Christian College",
  "Stella Maris College",
  "Women's Christian College",
  "Ethiraj College for Women",
  "Presidency College, Chennai",
  "Vivekananda College, Chennai",
  "D.G. Vaishnav College",
  "Guru Nanak College",
  "New College, Chennai",
  "Queen Mary's College",
  "Ramakrishna Mission Vivekananda College",
  "Sacred Heart College, Tirupattur",
  "St. Joseph's College, Tiruchirappalli",
  "Bishop Heber College",
  "National College, Tiruchirappalli",
  "Holy Cross College, Tiruchirappalli",
  "Jamal Mohamed College",
  "Government Arts College, Coimbatore",
  "PSG College of Arts and Science",
  "Bharathiar University",
  "Karunya Institute of Technology and Sciences",
  "Dr. N.G.P. Arts and Science College",
  "Sri Krishna Arts and Science College",
  "Kongunadu Arts and Science College",
  "GRD College of Science",
  "CMS College of Science and Commerce",
  "Park College of Engineering and Technology",
  "KPR Institute of Engineering and Technology",
  "Sri Ramakrishna Engineering College",
  "Sri Eshwar College of Engineering",
  "SNS College of Technology",
  "Adhiyamaan College of Engineering",
  "K.S. Rangasamy College of Technology",
  "Sona College of Technology",
  "Kongu Engineering College",
  "Bannari Amman Institute of Technology",
  "Kumaraguru College of Technology",
  "M. Kumarasamy College of Engineering",
  "Velalar College of Engineering and Technology",
  "Erode Sengunthar Engineering College",
  "Government College of Technology, Coimbatore",
  "Thiagarajar College of Engineering",
  "Madurai Kamaraj University",
  "Fatima College",
  "Lady Doak College",
  "American College, Madurai",
  "Mannar Thirumalai Naicker College",
  "Pasumpon Muthuramalinga Thevar College",
  "Vivekananda College, Agasteeswaram",
  "Scott Christian College",
  "St. Xavier's College, Palayamkottai",
  "Sarah Tucker College",
  "V.O. Chidambaram College",
  "Sri Paramakalyani College",
  "Government Arts College, Kumbakonam",
  "A.V.C. College (Autonomous)",
  "Annamalai University",
  "C. Abdul Hakeem College of Engineering & Technology",
  "Dhanalakshmi Srinivasan Engineering College",
  "K. Ramakrishnan College of Engineering",
  "M.A.M. College of Engineering",
  "P.S.N.A. College of Engineering and Technology",
  "R.M.K. Engineering College",
  "S.A. Engineering College",
  "Sri Sairam Engineering College",
  "Velammal Engineering College",
  "Meenakshi Sundararajan Engineering College",
  "Saveetha School of Engineering",
  "Chennai Institute of Technology",
  "Easwari Engineering College",
  "Jerusalem College of Engineering",
  "Misrimal Navajee Munoth Jain Engineering College",
  "P.B. College of Engineering",
  "Prince Dr. K. Vasudevan College of Engineering and Technology",
  "R.M.D. Engineering College",
  "Sri Venkateswara College of Engineering",
  "St. Joseph's Institute of Technology",
  "Tagore Engineering College",
  "Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College",
  "Vels Institute of Science, Technology & Advanced Studies",
  "Paavai Engineering College",
  "Bharathidasan Institute of Management",
  "National Institute of Fashion Technology, Chennai",
  "School of Architecture and Planning, Anna University",
  "Madras School of Social Work",
  "Stella Maris College (Autonomous)",
  "Women's Christian College (Autonomous)",
  "Loyola College of Education",
  "Presidency College (Autonomous)",
  "Queen Mary's College (Autonomous)",
  "Government College of Fine Arts, Chennai",
  "Dr. Ambedkar Government Law College, Chennai",
  "Madras Medical College",
  "Stanley Medical College",
  "Kilpauk Medical College",
  "Chengalpattu Medical College",
  "Coimbatore Medical College",
  "Madurai Medical College",
  "Thanjavur Medical College",
  "Tirunelveli Medical College",
  "Government Siddha Medical College, Chennai",
  "Government Unani Medical College, Chennai",
  "Government Homoeopathic Medical College, Tirumangalam",
  "Government Yoga and Naturopathy Medical College, Chennai",
  "Christian Medical College, Vellore",
  "Sri Ramachandra Institute of Higher Education and Research",
  "Saveetha Medical College",
  "Chettinad Hospital and Research Institute",
  "Meenakshi Ammal Dental College and Hospital",
  "Ragas Dental College and Hospital",
  "SRM Dental College",
  "Saveetha Dental College",
  "Sathyabama Dental College and Hospital",
  "Adhiparasakthi Dental College and Hospital",
  "Asan Memorial Dental College and Hospital",
  "Best Dental Science College",
  "C.S.I. College of Dental Sciences and Research",
  "D.A.V. Dental College",
  "J.K.K. Nattraja Dental College and Hospital",
  "K.S.R. Institute of Dental Science and Research",
  "Madha Dental College and Hospital",
  "P.S.G. Institute of Dental Sciences and Research",
  "Priyamvada Birla Institute of Dental Sciences and Research",
  "R.V.S. Dental College and Hospital",
  "Sree Balaji Dental College and Hospital",
  "Sri Mookambika Institute of Dental Sciences",
  "Sri Ramakrishna Dental College and Hospital",
  "Sri Venkateswara Dental College and Hospital",
  "Tagore Dental College and Hospital",
  "V.M.V. Dental College and Hospital",
  "Vivekanandha Dental College for Women",
  "Vinayaka Missions Sankarachariyar Dental College",
  "Velammal Dental College and Hospital",
  "Karpaga Vinayaga Institute of Dental Sciences",
  "Indira Gandhi Dental College and Hospital",
  "Jawaharlal Nehru Institute of Dental Sciences",
  "Mahatma Gandhi Dental College and Hospital",
  "IIT Bhubaneswar",
  "IIT Gandhinagar",
  "IIT Jodhpur",
  "IIT Patna",
  "IIT Ropar",
  "IIT Mandi",
  "IIT Indore",
  "IIT (BHU) Varanasi",
  "Oxford College of Engineering",
  "Adhiyamaan College of Engineering",
  "K.S. Rangasamy College of Technology",
  "Sona College of Technology",
  "Kongu Engineering College",
  "Bannari Amman Institute of Technology",
  "Kumaraguru College of Technology",
  "M. Kumarasamy College of Engineering",
  "Velalar College of Engineering and Technology",
  "Erode Sengunthar Engineering College",
  "Government College of Technology, Coimbatore",
  "Thiagarajar College of Engineering",
  "Madurai Kamaraj University",
  "Fatima College",
  "Lady Doak College",
  "American College, Madurai",
  "Mannar Thirumalai Naicker College",
  "Pasumpon Muthuramalinga Thevar College",
  "Vivekananda College, Agasteeswaram",
  "Scott Christian College",
  "St. Xavier's College, Palayamkottai",
  "Sarah Tucker College",
  "V.O. Chidambaram College",
  "Sri Paramakalyani College",
  "Government Arts College, Kumbakonam",
  "A.V.C. College (Autonomous)",
  "Annamalai University",
  "C. Abdul Hakeem College of Engineering & Technology",
  "Dhanalakshmi Srinivasan Engineering College",
  "K. Ramakrishnan College of Engineering",
  "M.A.M. College of Engineering",
  "P.S.N.A. College of Engineering and Technology",
  "R.M.K. Engineering College",
  "S.A. Engineering College",
  "Sri Sairam Engineering College",
  "Velammal Engineering College",
  "Meenakshi Sundararajan Engineering College",
  "Saveetha School of Engineering",
  "Chennai Institute of Technology",
  "Easwari Engineering College",
  "Jerusalem College of Engineering",
  "Misrimal Navajee Munoth Jain Engineering College",
  "P.B. College of Engineering",
  "Prince Dr. K. Vasudevan College of Engineering and Technology",
  "R.M.D. Engineering College",
  "Sri Venkateswara College of Engineering",
  "St. Joseph's Institute of Technology",
  "Tagore Engineering College",
  "Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College",
  "Vels Institute of Science, Technology & Advanced Studies",
  "Paavai Engineering College",
  "Bharathidasan Institute of Management",
  "National Institute of Fashion Technology, Chennai",
  "School of Architecture and Planning, Anna University",
  "Madras School of Social Work",
  "Stella Maris College (Autonomous)",
  "Women's Christian College (Autonomous)",
  "Loyola College of Education",
  "Presidency College (Autonomous)",
  "Queen Mary's College (Autonomous)",
  "Government College of Fine Arts, Chennai",
  "Dr. Ambedkar Government Law College, Chennai",
  "Madras Medical College",
  "Stanley Medical College",
  "Kilpauk Medical College",
  "Chengalpattu Medical College",
  "Coimbatore Medical College",
  "Madurai Medical College",
  "Thanjavur Medical College",
  "Tirunelveli Medical College",
  "Government Siddha Medical College, Chennai",
  "Government Unani Medical College, Chennai",
  "Government Homoeopathic Medical College, Tirumangalam",
  "Government Yoga and Naturopathy Medical College, Chennai",
  "Christian Medical College, Vellore",
  "Sri Ramachandra Institute of Higher Education and Research",
  "Saveetha Medical College",
  "Chettinad Hospital and Research Institute",
  "Meenakshi Ammal Dental College and Hospital",
  "Ragas Dental College and Hospital",
  "SRM Dental College",
  "Saveetha Dental College",
  "Sathyabama Dental College and Hospital",
  "Adhiparasakthi Dental College and Hospital",
  "Asan Memorial Dental College and Hospital",
  "Best Dental Science College",
  "C.S.I. College of Dental Sciences and Research",
  "D.A.V. Dental College",
  "J.K.K. Nattraja Dental College and Hospital",
  "K.S.R. Institute of Dental Science and Research",
  "Madha Dental College and Hospital",
  "P.S.G. Institute of Dental Sciences and Research",
  "Priyamvada Birla Institute of Dental Sciences and Research",
  "R.V.S. Dental College and Hospital",
  "Sree Balaji Dental College and Hospital",
  "Sri Mookambika Institute of Dental Sciences",
  "Sri Ramakrishna Dental College and Hospital",
  "Sri Venkateswara Dental College and Hospital",
  "Tagore Dental College and Hospital",
  "V.M.V. Dental College and Hospital",
  "Vivekanandha Dental College for Women",
  "Vinayaka Missions Sankarachariyar Dental College",
  "Velammal Dental College and Hospital",
  "Karpaga Vinayaga Institute of Dental Sciences",
  "Indira Gandhi Dental College and Hospital",
  "Jawaharlal Nehru Institute of Dental Sciences",
  "Mahatma Gandhi Dental College and Hospital",
  
];